# A generic, single database configuration.

[alembic]
# path to migration scripts
script_location = alembic

# template used to generate new migration files
# file_template = %%(year)d_%%(month).2d_%%(day).2d_%%(hour).2d%%(minute).2d-%%(rev)s_%%(slug)s

# sys.path pathlists to be prepended to sys.path in env.py.
# prepend_syspath = .

# timezone to use when rendering the date within the migration file
# timezone = UTC

# max length of characters to associate with the "slug" field
# truncate_slug_length = 40

# set to 'true' to run the environment during
# the 'revision' command, regardless of autogenerate
# revision_environment = false

# set to 'true' to allow modules to be imported from sys.path
# without necessarily being inside the script_location
# (e.g. models or utilities located outside alembic)
# version_locations = %(here)s/bar:%(here)s/bat

# version path separator; defaults to "os.pathsep".
# version_path_separator = :

# set to 'true' to search source files recursively for
# revision scripts
# recursive_version_locations = false

# the database connection URL is usually defined or overridden in env.py
sqlalchemy.url = postgresql://postgres:password@localhost:5432/smarthire

[post_write_hooks]
# post_write_hooks defines scripts or Python functions that are run
# on newly generated revision scripts. For example, to run ruff formatting:
# hooks = ruff
# ruff.type = console_scripts
# ruff.entrypoint = ruff
# ruff.options = format REVISION_SCRIPT_FILE

# Logging configuration
[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARNING
handlers = console
qualname =

[logger_sqlalchemy]
level = WARNING
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stdout,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
