export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  DASHBOARD: '/dashboard',
  PROFILE: '/profile',
  RESUME: '/resume',
  EDUCATION: '/education',
  EXPERIENCE: '/experience',
  SKILLS: '/skills',
  JOBS: '/jobs',
  SAVED_JOBS: '/saved-jobs',
  APPLICATIONS: '/applications',
  RECRUITER: '/recruiter',
  RECRUITER_JOBS: '/recruiter/jobs',
  RECRUITER_CREATE_JOB: '/recruiter/jobs/create',
  RECRUITER_EDIT_JOB: '/recruiter/jobs/:id/edit',
  RECRUITER_APPLICANT_DETAILS: '/recruiter/applications/:id',
  RECRUITER_APPLICANTS: '/recruiter/applicants',
  RECRUITER_PROFILE: '/recruiter/profile',
  RECRUITER_COMPANY_SETTINGS: '/recruiter/company/settings',
  COMPANY: '/company',
  COMPANY_SETTINGS: '/company/settings',
  ADMIN: '/admin',
  UNAUTHORIZED: '/unauthorized',
};
