"""Add file metadata to Resume

Revision ID: 30fa3408e169
Revises: 53417a8da018
Create Date: 2026-07-19 11:42:21.552739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30fa3408e169'
down_revision: Union[str, None] = '53417a8da018'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('file_name', sa.String(length=255), nullable=True, comment='Original name of the uploaded PDF file'))
    op.add_column('resumes', sa.Column('file_path', sa.String(length=255), nullable=True, comment='Local file system storage path'))
    op.add_column('resumes', sa.Column('file_size', sa.Integer(), nullable=True, comment='File size in bytes'))
    op.add_column('resumes', sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Resume uploaded timestamp'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'uploaded_at')
    op.drop_column('resumes', 'file_size')
    op.drop_column('resumes', 'file_path')
    op.drop_column('resumes', 'file_name')
    # ### end Alembic commands ###
