"""Add company details and owner

Revision ID: 33421ae4678e
Revises: d3477545dc7a
Create Date: 2026-07-19 10:03:17.420461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33421ae4678e'
down_revision: Union[str, None] = 'd3477545dc7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('company_code', sa.String(length=50), nullable=False, comment='Unique auto-generated code identifying the company'))
    op.add_column('companies', sa.Column('owner_id', sa.BigInteger(), nullable=False, comment='Foreign key linking to the user account that owns the company'))
    op.add_column('companies', sa.Column('industry', sa.String(length=100), nullable=False, comment='Industry domain categorizing the company (e.g. Technology, Finance)'))
    op.add_column('companies', sa.Column('company_size', sa.String(length=50), nullable=False, comment='Company employee size range category'))
    op.add_column('companies', sa.Column('location', sa.String(length=100), nullable=False, comment='Primary geographic headquarter location'))
    op.create_index(op.f('ix_companies_company_code'), 'companies', ['company_code'], unique=True)
    op.create_index(op.f('ix_companies_owner_id'), 'companies', ['owner_id'], unique=False)
    op.create_foreign_key(None, 'companies', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'companies', type_='foreignkey')
    op.drop_index(op.f('ix_companies_owner_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_company_code'), table_name='companies')
    op.drop_column('companies', 'location')
    op.drop_column('companies', 'company_size')
    op.drop_column('companies', 'industry')
    op.drop_column('companies', 'owner_id')
    op.drop_column('companies', 'company_code')
    # ### end Alembic commands ###
