"""update_applications_table

Revision ID: 3b99a64c52d1
Revises: e5ed0a26903d
Create Date: 2026-07-19 13:39:12.186631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b99a64c52d1'
down_revision: Union[str, None] = 'e5ed0a26903d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('status', sa.String(length=50), nullable=False, comment='Current status of the job application'))
    op.add_column('applications', sa.Column('resume_id', sa.BigInteger(), nullable=True, comment='Foreign key linking to the resume used for the application'))
    op.add_column('applications', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('applications', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_applications_resume_id'), 'applications', ['resume_id'], unique=False)
    op.create_foreign_key(None, 'applications', 'resumes', ['resume_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.drop_index(op.f('ix_applications_resume_id'), table_name='applications')
    op.drop_column('applications', 'updated_at')
    op.drop_column('applications', 'created_at')
    op.drop_column('applications', 'resume_id')
    op.drop_column('applications', 'status')
    # ### end Alembic commands ###
