"""Add company invitations and link user to company

Revision ID: 4d483dd94fc6
Revises: 33421ae4678e
Create Date: 2026-07-19 10:18:33.449892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d483dd94fc6'
down_revision: Union[str, None] = '33421ae4678e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_invitations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Unique identifier for the invitation'),
    sa.Column('company_id', sa.BigInteger(), nullable=False, comment='Foreign key linking to the inviting company'),
    sa.Column('recruiter_email', sa.String(length=255), nullable=False, comment='Email address of the invited recruiter'),
    sa.Column('invitation_token', sa.String(length=255), nullable=False, comment='Unique token string to validate invitation acceptance'),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'EXPIRED', name='invitation_status_enum', inherit_schema=True), nullable=False, comment='Status states: pending, accepted, expired'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='Expiration timestamp when invitation token expires'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_invitations_company_id'), 'company_invitations', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_invitations_id'), 'company_invitations', ['id'], unique=False)
    op.create_index(op.f('ix_company_invitations_invitation_token'), 'company_invitations', ['invitation_token'], unique=True)
    op.create_index(op.f('ix_company_invitations_recruiter_email'), 'company_invitations', ['recruiter_email'], unique=False)
    op.add_column('users', sa.Column('company_id', sa.BigInteger(), nullable=True, comment="Foreign key linking to the recruiter's company"))
    op.create_index(op.f('ix_users_company_id'), 'users', ['company_id'], unique=False)
    op.create_foreign_key(None, 'users', 'companies', ['company_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_company_id'), table_name='users')
    op.drop_column('users', 'company_id')
    op.drop_index(op.f('ix_company_invitations_recruiter_email'), table_name='company_invitations')
    op.drop_index(op.f('ix_company_invitations_invitation_token'), table_name='company_invitations')
    op.drop_index(op.f('ix_company_invitations_id'), table_name='company_invitations')
    op.drop_index(op.f('ix_company_invitations_company_id'), table_name='company_invitations')
    op.drop_table('company_invitations')
    # ### end Alembic commands ###
