"""Add JobSeekerProfile

Revision ID: 53417a8da018
Revises: 2a80f4846e7f
Create Date: 2026-07-19 11:40:36.346924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53417a8da018'
down_revision: Union[str, None] = '2a80f4846e7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_seeker_profiles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Unique identifier for the profile'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='Foreign key linking to the owner user account'),
    sa.Column('full_name', sa.String(length=100), nullable=False, comment='Full name of the job seeker'),
    sa.Column('phone_number', sa.String(length=20), nullable=False, comment='Phone number of the job seeker'),
    sa.Column('date_of_birth', sa.Date(), nullable=False, comment='Date of birth of the job seeker'),
    sa.Column('gender', sa.String(length=20), nullable=False, comment='Gender of the job seeker'),
    sa.Column('address', sa.String(length=255), nullable=False, comment='Street address'),
    sa.Column('city', sa.String(length=100), nullable=False, comment='City of residence'),
    sa.Column('state', sa.String(length=100), nullable=False, comment='State of residence'),
    sa.Column('country', sa.String(length=100), nullable=False, comment='Country of residence'),
    sa.Column('linkedin_url', sa.String(length=255), nullable=True, comment='LinkedIn profile URL'),
    sa.Column('github_url', sa.String(length=255), nullable=True, comment='GitHub profile URL'),
    sa.Column('portfolio_url', sa.String(length=255), nullable=True, comment='Portfolio URL'),
    sa.Column('professional_summary', sa.Text(), nullable=True, comment='Professional summary'),
    sa.Column('profile_photo_url', sa.String(length=255), nullable=True, comment='Profile picture URL'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_seeker_profiles_id'), 'job_seeker_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_job_seeker_profiles_user_id'), 'job_seeker_profiles', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_seeker_profiles_user_id'), table_name='job_seeker_profiles')
    op.drop_index(op.f('ix_job_seeker_profiles_id'), table_name='job_seeker_profiles')
    op.drop_table('job_seeker_profiles')
    # ### end Alembic commands ###
