"""create_job_recruiters_table

Revision ID: 6f8aa34129b8
Revises: 3b99a64c52d1
Create Date: 2026-08-11 13:23:07.931277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6f8aa34129b8'
down_revision: Union[str, None] = '3b99a64c52d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_recruiters',
    sa.Column('job_id', sa.BigInteger(), nullable=False, comment='Foreign key linking to the job listing'),
    sa.Column('recruiter_id', sa.BigInteger(), nullable=False, comment='Foreign key linking to the assigned recruiter user'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when recruiter was assigned to job'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recruiter_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('job_id', 'recruiter_id')
    )
    op.create_index(op.f('ix_job_recruiters_job_id'), 'job_recruiters', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_recruiters_recruiter_id'), 'job_recruiters', ['recruiter_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_recruiters_recruiter_id'), table_name='job_recruiters')
    op.drop_index(op.f('ix_job_recruiters_job_id'), table_name='job_recruiters')
    op.drop_table('job_recruiters')
    # ### end Alembic commands ###
