"""Update Education fields

Revision ID: 74dd0aefc449
Revises: 30fa3408e169
Create Date: 2026-07-19 11:44:00.587212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74dd0aefc449'
down_revision: Union[str, None] = '30fa3408e169'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('education', sa.Column('start_date', sa.Date(), nullable=False, comment='Academic start date'))
    op.add_column('education', sa.Column('end_date', sa.Date(), nullable=True, comment='Academic end date'))
    op.add_column('education', sa.Column('grade', sa.String(length=50), nullable=True, comment='Cumulative Grade / CGPA achieved'))
    op.add_column('education', sa.Column('description', sa.Text(), nullable=True, comment='Additional description, activities, or achievements'))
    op.drop_column('education', 'cgpa')
    op.drop_column('education', 'start_year')
    op.drop_column('education', 'end_year')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('education', sa.Column('end_year', sa.SMALLINT(), autoincrement=False, nullable=False, comment='Calendar year studies completed or expected to conclude'))
    op.add_column('education', sa.Column('start_year', sa.SMALLINT(), autoincrement=False, nullable=False, comment='Calendar year academic studies started'))
    op.add_column('education', sa.Column('cgpa', sa.NUMERIC(precision=4, scale=2), autoincrement=False, nullable=True, comment='Cumulative Grade Point Average (CGPA) - e.g., 3.85 / 4.00'))
    op.drop_column('education', 'description')
    op.drop_column('education', 'grade')
    op.drop_column('education', 'end_date')
    op.drop_column('education', 'start_date')
    # ### end Alembic commands ###
