"""add_employment_type_and_location_to_experience

Revision ID: b2257bb51720
Revises: 74dd0aefc449
Create Date: 2026-07-19 13:12:25.623758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2257bb51720'
down_revision: Union[str, None] = '74dd0aefc449'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experience', sa.Column('employment_type', sa.String(length=100), nullable=True, comment='Employment type (e.g. Full-time, Part-time)'))
    op.add_column('experience', sa.Column('location', sa.String(length=100), nullable=True, comment='Work location (e.g. London, Remote)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('experience', 'location')
    op.drop_column('experience', 'employment_type')
    # ### end Alembic commands ###
