"""Initial migration

Revision ID: d3477545dc7a
Revises: None
Create Date: 2026-07-19 00:46:06.974459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3477545dc7a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Unique identifier for the company'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Legal name of the employer company'),
    sa.Column('description', sa.Text(), nullable=True, comment='Company description and profile overview'),
    sa.Column('logo_url', sa.String(length=255), nullable=True, comment='URL pointing to the stored logo image file'),
    sa.Column('website', sa.String(length=255), nullable=True, comment="URL pointing to the company's website"),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_table('skills',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Unique identifier for the skill'),
    sa.Column('skill_name', sa.String(length=100), nullable=False, comment='Unique name of the skill'),
    sa.Column('category', sa.String(length=100), nullable=False, comment='Category grouping the skill (e.g., Frontend, Database)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the skill was added to the catalog'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skills_id'), 'skills', ['id'], unique=False)
    op.create_index(op.f('ix_skills_skill_name'), 'skills', ['skill_name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Unique identifier for the user account'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Full name of the user'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='Unique email address used for credentials logging'),
    sa.Column('password', sa.String(length=255), nullable=False, comment='Hashed secure credential password string'),
    sa.Column('role', sa.Enum('JOBSEEKER', 'RECRUITER', 'ADMIN', name='user_role_enum', inherit_schema=True), nullable=False, comment='Role determining system access permissions'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='User phone number including country prefix code'),
    sa.Column('profile_image', sa.String(length=255), nullable=True, comment='URL pointing to the stored profile picture image'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Unique identifier for the job posting'),
    sa.Column('company_id', sa.BigInteger(), nullable=False, comment='Foreign key linking to the employer company record'),
    sa.Column('title', sa.String(length=100), nullable=False, comment='Job title designation'),
    sa.Column('description', sa.Text(), nullable=False, comment='Detailed job description, responsibilities, and requirements text'),
    sa.Column('location', sa.String(length=100), nullable=False, comment="Physical location (City, State/Country) or 'Remote'"),
    sa.Column('job_type', sa.Enum('FULL_TIME', 'PART_TIME', 'CONTRACT', 'INTERNSHIP', name='job_type_enum', inherit_schema=True), nullable=False, comment='Employment type (Full-time, Part-time, etc.)'),
    sa.Column('experience_level', sa.Enum('FRESHER', 'ENTRY', 'MID', 'SENIOR', name='experience_level_enum', inherit_schema=True), nullable=False, comment='Target candidate experience range'),
    sa.Column('salary_min', sa.Numeric(precision=12, scale=2), nullable=True, comment='Minimum package salary range'),
    sa.Column('salary_max', sa.Numeric(precision=12, scale=2), nullable=True, comment='Maximum package salary range'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_company_id'), 'jobs', ['company_id'], unique=False)
    op.create_index(op.f('ix_jobs_id'), 'jobs', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Unique identifier for the notification'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='Foreign key linking to the recipient user account'),
    sa.Column('title', sa.String(length=150), nullable=False, comment='Notification summary or title text'),
    sa.Column('message', sa.Text(), nullable=False, comment='Comprehensive message body text'),
    sa.Column('is_read', sa.Boolean(), nullable=False, comment='True if the user has read the notification'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the notification was created'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('resumes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Unique identifier for the resume'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='Foreign key linking to the owner user account'),
    sa.Column('summary', sa.Text(), nullable=True, comment='Professional summary overview text'),
    sa.Column('github_url', sa.String(length=255), nullable=True, comment='Candidate GitHub profile link'),
    sa.Column('linkedin_url', sa.String(length=255), nullable=True, comment='Candidate LinkedIn profile link'),
    sa.Column('portfolio_url', sa.String(length=255), nullable=True, comment='Candidate personal portfolio website link'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resumes_id'), 'resumes', ['id'], unique=False)
    op.create_index(op.f('ix_resumes_user_id'), 'resumes', ['user_id'], unique=True)
    op.create_table('certifications',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Unique identifier for the certification record'),
    sa.Column('resume_id', sa.BigInteger(), nullable=False, comment='Foreign key linking to the associated resume'),
    sa.Column('certificate_name', sa.String(length=150), nullable=False, comment='Name of the certification'),
    sa.Column('issuing_organization', sa.String(length=150), nullable=False, comment='Organization issuing the certification'),
    sa.Column('issue_date', sa.Date(), nullable=False, comment='Date of certification issue'),
    sa.Column('credential_url', sa.String(length=255), nullable=True, comment='Link to verify credential certification validation (optional)'),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_certifications_id'), 'certifications', ['id'], unique=False)
    op.create_index(op.f('ix_certifications_resume_id'), 'certifications', ['resume_id'], unique=False)
    op.create_table('education',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Unique identifier for the education record'),
    sa.Column('resume_id', sa.BigInteger(), nullable=False, comment='Foreign key linking to the associated resume'),
    sa.Column('institution_name', sa.String(length=150), nullable=False, comment='Name of the university, college, or school'),
    sa.Column('degree', sa.String(length=100), nullable=False, comment='Degree attained'),
    sa.Column('field_of_study', sa.String(length=100), nullable=False, comment='Major or field of study'),
    sa.Column('start_year', sa.SmallInteger(), nullable=False, comment='Calendar year academic studies started'),
    sa.Column('end_year', sa.SmallInteger(), nullable=False, comment='Calendar year studies completed or expected to conclude'),
    sa.Column('cgpa', sa.Numeric(precision=4, scale=2), nullable=True, comment='Cumulative Grade Point Average (CGPA) - e.g., 3.85 / 4.00'),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_education_id'), 'education', ['id'], unique=False)
    op.create_index(op.f('ix_education_resume_id'), 'education', ['resume_id'], unique=False)
    op.create_table('experience',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Unique identifier for the experience record'),
    sa.Column('resume_id', sa.BigInteger(), nullable=False, comment='Foreign key linking to the associated resume'),
    sa.Column('company_name', sa.String(length=150), nullable=False, comment='Name of the employing company'),
    sa.Column('job_title', sa.String(length=100), nullable=False, comment='Professional designation (e.g. Senior Software Engineer)'),
    sa.Column('start_date', sa.Date(), nullable=False, comment='Employment commencement date'),
    sa.Column('end_date', sa.Date(), nullable=True, comment='Employment conclusion date'),
    sa.Column('currently_working', sa.Boolean(), nullable=False, comment='True if the candidate currently holds this position'),
    sa.Column('description', sa.Text(), nullable=False, comment='Details regarding responsibilities and accomplishments in this role'),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experience_id'), 'experience', ['id'], unique=False)
    op.create_index(op.f('ix_experience_resume_id'), 'experience', ['resume_id'], unique=False)
    op.create_table('hiring_pipelines',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Unique identifier for the hiring pipeline'),
    sa.Column('job_id', sa.BigInteger(), nullable=False, comment='Foreign key linking to the associated job posting'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp indicating when the pipeline was created'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hiring_pipelines_id'), 'hiring_pipelines', ['id'], unique=False)
    op.create_index(op.f('ix_hiring_pipelines_job_id'), 'hiring_pipelines', ['job_id'], unique=True)
    op.create_table('job_required_skills',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Unique identifier for the job-skill mapping'),
    sa.Column('job_id', sa.BigInteger(), nullable=False, comment='Foreign key linking to the associated job posting'),
    sa.Column('skill_id', sa.BigInteger(), nullable=False, comment='Foreign key linking to the associated skill requirement'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'skill_id', name='uq_job_required_skills_job_skill')
    )
    op.create_index(op.f('ix_job_required_skills_id'), 'job_required_skills', ['id'], unique=False)
    op.create_index(op.f('ix_job_required_skills_job_id'), 'job_required_skills', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_required_skills_skill_id'), 'job_required_skills', ['skill_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Unique identifier for the project record'),
    sa.Column('resume_id', sa.BigInteger(), nullable=False, comment='Foreign key linking to the associated resume'),
    sa.Column('project_title', sa.String(length=100), nullable=False, comment='Title or name of the project'),
    sa.Column('description', sa.Text(), nullable=False, comment='Detailed explanation of the project work, scope, and target outcomes'),
    sa.Column('technologies_used', sa.String(length=255), nullable=False, comment='Comma-separated list or description of technologies used'),
    sa.Column('github_url', sa.String(length=255), nullable=True, comment='Repository link on GitHub/GitLab (optional)'),
    sa.Column('live_demo_url', sa.String(length=255), nullable=True, comment='URL pointing to the running live application demo (optional)'),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_resume_id'), 'projects', ['resume_id'], unique=False)
    op.create_table('resume_skills',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Unique identifier for the resume-skill mapping'),
    sa.Column('resume_id', sa.BigInteger(), nullable=False, comment='Foreign key linking to the associated resume record'),
    sa.Column('skill_id', sa.BigInteger(), nullable=False, comment='Foreign key linking to the associated skill record'),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resume_id', 'skill_id', name='uq_resume_skills_resume_skill')
    )
    op.create_index(op.f('ix_resume_skills_id'), 'resume_skills', ['id'], unique=False)
    op.create_index(op.f('ix_resume_skills_resume_id'), 'resume_skills', ['resume_id'], unique=False)
    op.create_index(op.f('ix_resume_skills_skill_id'), 'resume_skills', ['skill_id'], unique=False)
    op.create_table('pipeline_stages',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Unique identifier for the pipeline stage'),
    sa.Column('pipeline_id', sa.BigInteger(), nullable=False, comment='Foreign key linking to the parent hiring pipeline'),
    sa.Column('stage_name', sa.String(length=100), nullable=False, comment='Label or name of the hiring stage'),
    sa.Column('stage_order', sa.Integer(), nullable=False, comment='Integer determining the chronological order of the stage'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp indicating when the stage was created'),
    sa.ForeignKeyConstraint(['pipeline_id'], ['hiring_pipelines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_stages_id'), 'pipeline_stages', ['id'], unique=False)
    op.create_index(op.f('ix_pipeline_stages_pipeline_id'), 'pipeline_stages', ['pipeline_id'], unique=False)
    op.create_table('applications',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Unique identifier for the application record'),
    sa.Column('job_id', sa.BigInteger(), nullable=False, comment='Foreign key linking to the applied job posting'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='Foreign key linking to the applicant user account'),
    sa.Column('match_score', sa.Numeric(precision=5, scale=2), nullable=True, comment='AI-calculated profile-job relevance match percentage score'),
    sa.Column('current_stage_id', sa.BigInteger(), nullable=True, comment='Foreign key linking to the active hiring stage of the application'),
    sa.Column('applied_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp representing application submit time'),
    sa.ForeignKeyConstraint(['current_stage_id'], ['pipeline_stages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'job_id', name='uq_applications_user_job')
    )
    op.create_index(op.f('ix_applications_current_stage_id'), 'applications', ['current_stage_id'], unique=False)
    op.create_index(op.f('ix_applications_id'), 'applications', ['id'], unique=False)
    op.create_index(op.f('ix_applications_job_id'), 'applications', ['job_id'], unique=False)
    op.create_index(op.f('ix_applications_user_id'), 'applications', ['user_id'], unique=False)
    op.create_table('application_status_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Unique identifier for the history entry'),
    sa.Column('application_id', sa.BigInteger(), nullable=False, comment='Foreign key linking to the parent application'),
    sa.Column('stage_id', sa.BigInteger(), nullable=False, comment='Foreign key linking to the pipeline stage status'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='Foreign key linking to the user who triggered the update'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the transition occurred'),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stage_id'], ['pipeline_stages.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_status_history_application_id'), 'application_status_history', ['application_id'], unique=False)
    op.create_index(op.f('ix_application_status_history_id'), 'application_status_history', ['id'], unique=False)
    op.create_index(op.f('ix_application_status_history_stage_id'), 'application_status_history', ['stage_id'], unique=False)
    op.create_index(op.f('ix_application_status_history_updated_by'), 'application_status_history', ['updated_by'], unique=False)
    op.create_table('recruiter_notes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Unique identifier for the note'),
    sa.Column('application_id', sa.BigInteger(), nullable=False, comment='Foreign key linking to the evaluated application record'),
    sa.Column('recruiter_id', sa.BigInteger(), nullable=True, comment='Foreign key linking to the recruiter who authored the note'),
    sa.Column('note', sa.Text(), nullable=False, comment='Evaluation feedback or interview notes text'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recruiter_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recruiter_notes_application_id'), 'recruiter_notes', ['application_id'], unique=False)
    op.create_index(op.f('ix_recruiter_notes_id'), 'recruiter_notes', ['id'], unique=False)
    op.create_index(op.f('ix_recruiter_notes_recruiter_id'), 'recruiter_notes', ['recruiter_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recruiter_notes_recruiter_id'), table_name='recruiter_notes')
    op.drop_index(op.f('ix_recruiter_notes_id'), table_name='recruiter_notes')
    op.drop_index(op.f('ix_recruiter_notes_application_id'), table_name='recruiter_notes')
    op.drop_table('recruiter_notes')
    op.drop_index(op.f('ix_application_status_history_updated_by'), table_name='application_status_history')
    op.drop_index(op.f('ix_application_status_history_stage_id'), table_name='application_status_history')
    op.drop_index(op.f('ix_application_status_history_id'), table_name='application_status_history')
    op.drop_index(op.f('ix_application_status_history_application_id'), table_name='application_status_history')
    op.drop_table('application_status_history')
    op.drop_index(op.f('ix_applications_user_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_job_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_current_stage_id'), table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_pipeline_stages_pipeline_id'), table_name='pipeline_stages')
    op.drop_index(op.f('ix_pipeline_stages_id'), table_name='pipeline_stages')
    op.drop_table('pipeline_stages')
    op.drop_index(op.f('ix_resume_skills_skill_id'), table_name='resume_skills')
    op.drop_index(op.f('ix_resume_skills_resume_id'), table_name='resume_skills')
    op.drop_index(op.f('ix_resume_skills_id'), table_name='resume_skills')
    op.drop_table('resume_skills')
    op.drop_index(op.f('ix_projects_resume_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_job_required_skills_skill_id'), table_name='job_required_skills')
    op.drop_index(op.f('ix_job_required_skills_job_id'), table_name='job_required_skills')
    op.drop_index(op.f('ix_job_required_skills_id'), table_name='job_required_skills')
    op.drop_table('job_required_skills')
    op.drop_index(op.f('ix_hiring_pipelines_job_id'), table_name='hiring_pipelines')
    op.drop_index(op.f('ix_hiring_pipelines_id'), table_name='hiring_pipelines')
    op.drop_table('hiring_pipelines')
    op.drop_index(op.f('ix_experience_resume_id'), table_name='experience')
    op.drop_index(op.f('ix_experience_id'), table_name='experience')
    op.drop_table('experience')
    op.drop_index(op.f('ix_education_resume_id'), table_name='education')
    op.drop_index(op.f('ix_education_id'), table_name='education')
    op.drop_table('education')
    op.drop_index(op.f('ix_certifications_resume_id'), table_name='certifications')
    op.drop_index(op.f('ix_certifications_id'), table_name='certifications')
    op.drop_table('certifications')
    op.drop_index(op.f('ix_resumes_user_id'), table_name='resumes')
    op.drop_index(op.f('ix_resumes_id'), table_name='resumes')
    op.drop_table('resumes')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_jobs_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_company_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_skills_skill_name'), table_name='skills')
    op.drop_index(op.f('ix_skills_id'), table_name='skills')
    op.drop_table('skills')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
