"""Add is_deleted to Job

Revision ID: d76802dd1fee
Revises: fc21734f57e7
Create Date: 2026-07-19 10:33:25.418201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd76802dd1fee'
down_revision: Union[str, None] = 'fc21734f57e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Flag indicating if the job posting is soft-deleted'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'is_deleted')
    # ### end Alembic commands ###
