"""sync alembic schema

Revision ID: f0282cf311dd
Revises: 98d796941adb
Create Date: 2026-08-15 14:58:18.765798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f0282cf311dd'
down_revision: Union[str, None] = '98d796941adb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TABLE IF EXISTS ai_skill_matchings CASCADE;")
    op.execute("DROP TABLE IF EXISTS ai_insights_history CASCADE;")
    op.execute("DROP TABLE IF EXISTS ai_match_scores CASCADE;")
    op.alter_column('companies', 'logo_url',
               existing_type=sa.TEXT(),
               comment='URL pointing to the stored logo image file or Base64 string',
               existing_comment='URL pointing to the stored logo image file',
               existing_nullable=True)
    op.alter_column('job_seeker_profiles', 'profile_photo_url',
               existing_type=sa.TEXT(),
               comment='Profile picture URL or Base64 string',
               existing_comment='Profile picture URL',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job_seeker_profiles', 'profile_photo_url',
               existing_type=sa.TEXT(),
               comment='Profile picture URL',
               existing_comment='Profile picture URL or Base64 string',
               existing_nullable=True)
    op.alter_column('companies', 'logo_url',
               existing_type=sa.TEXT(),
               comment='URL pointing to the stored logo image file',
               existing_comment='URL pointing to the stored logo image file or Base64 string',
               existing_nullable=True)
    op.create_table('ai_match_scores',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('match_data', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='ai_match_scores_pkey')
    )
    op.create_table('ai_insights_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('insight_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('insight_data', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='ai_insights_history_pkey')
    )
    op.create_table('ai_skill_matchings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('overall_coverage', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('matching_data', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='ai_skill_matchings_pkey')
    )
    # ### end Alembic commands ###
